openapi: 3.0.3
info:
  title: Swagger SOSCOFFE - OpenAPI 3.0
  description: |-
    Essa é a documentação de um WebServer de assinaturas chamado SOSCOFFE
  
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:3000/

tags:
  - name: planos
    description: tudo sobre planos

  - name: assinaturas
    description: tudo sobre assinatura

paths:
  /planos:
    get:
      tags:
        - planos
      summary: Retorna todos os planos existentes
      description: Retorna todos os planos existentes
      operationId: getPlanos
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Planos'
        '500':
          description: Internal Server Error
    post:
      tags:
        - planos
      summary: Insere um novo plano
      description: Insere um novo plano
      operationId: postPlanos
      requestBody:
        description: Criando um objeto de plano
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanosSemID'
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
  /planos/{id}:
    get:
      tags:
        - planos
      summary: busca um plano por id
      description: busca e retorna um plano por id
      operationId: getPlanosById
      parameters:
        - name: id
          in: path
          description: ID do plano que será retornado
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planos'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanoNotFound'
        '500':
          description: Internal Server Error
    put:
      tags:
        - planos
      summary: atualiza um plano
      description: atualiza e retorna um plano
      operationId: putPlanos
      parameters:
        - name: id
          in: path
          description: ID do plano que será retornado
          required: true
          schema:
            type: integer
            format: int
      requestBody:
        description: Criando um objeto de plano
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanosSemID'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editSucessfull'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanoNotFound'
        '500':
          description: Internal Server Error
    delete:
      tags:
        - planos
      summary: atualiza um plano
      description: atualiza e retorna um plano
      operationId: deletePlanos
      parameters:
        - name: id
          in: path
          description: ID do plano que será retornado
          required: true
          schema:
            type: integer
            format: int
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deletSucessfull'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanoNotFound'
        '500':
          description: Internal Server Error
  
  /assinaturas:
    get:
      tags:
        - assinaturas
      summary: Retorna todos as assinatura existentes
      description: Retorna todos as assinatura existentes
      operationId: getAssinatura
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assinatura'
        '500':
          description: Internal Server Error
    post:
      tags:
        - assinaturas
      summary: Insere uma nova assinatura
      description: Insere uma nova assinatura
      operationId: postAssinatura
      requestBody:
        description: Criando um objeto de assinatura
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssinaturaSemId'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssinaturaSucessfull'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioJaAssinou'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanoNotFound'
        '500':
          description: Internal Server Error
  
  /assinaturas/{id}:
    get:
      tags:
        - assinaturas
      summary: busca uma assinatura por id
      description: busca e retorna um assinatura por id
      operationId: getAssinaturaById
      parameters:
        - name: id
          in: path
          description: ID da assinatura que será retornada
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assinatura'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioNotFound'
        '500':
          description: Internal Server Error
    put:
      tags:
        - assinaturas
      summary: atualiza uma assinatura
      description: atualiza e retorna uma assinatura
      operationId: putAssinatura
      parameters:
        - name: id
          in: path
          description: ID da assinatura que será retornada
          required: true
          schema:
            type: integer
            format: int
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssinaturaDesativada'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioSemAssinatura'
        '500':
          description: Internal Server Error
  /assinaturas/usuario/{id}:
    get:
      tags:
        - assinaturas
      summary: busca e retorna as assinaturas por id do usuario
      description: busca e retorna as assinaturas por id do usuario
      operationId: getAssinaturaByIdUsuario
      parameters:
        - name: id
          in: path
          description: ID da usuario 
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assinatura'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssinaturaUsuarioNotFound'
        '500':
          description: Internal Server Error
  /assinaturas/usuario/ativa/{id}:
    get:
      tags:
        - assinaturas
      summary: busca e retorna as assinaturas ativa por id do usuario
      description: busca e retorna as assinatura ativa por id do usuario
      operationId: getAssinaturaAtivaByIdUsuario
      parameters:
        - name: id
          in: path
          description: ID da usuario 
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assinatura'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssinaturaUsuarioNotFound'
        '500':
          description: Internal Server Error
components:
  schemas:
    Planos:
      type: object
      properties:
        id_planos:
          type: integer
          format: int
          example: 10
        nome_plano:
          type: string
          format: varchar45
          example: platina
        valor:
          type: number
          format: float
          example: 99.90
    PlanosSemID:
      type: object
      properties:
        nome_plano:
          type: string
          format: varchar45
          example: platina
        valor:
          type: number
          format: float
          example: 99.90
    PlanoNotFound:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Plano não encontrado
    editSucessfull:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Plano editado com sucesso
    deletSucessfull:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Plano deletado com sucesso
    
    Assinatura:
      type: object
      properties:
        id_assinatura:
          type: integer
          format: int
          example: 10
        id_usuario:
          type: integer
          format: int
          example: 10
        fk_id_planos:
          type: integer
          format: int
          example: 10
        assinatura_ativa:
          type: boolean
          format: boolean
          example: true
        data_inicio:
          type: string
          format: date
          example: 2023-11-29
        data_fim:
          type: string
          format: date
          example: 2023-12-01
    AssinaturaSemId:
      type: object
      properties:
        id_usuario:
          type: integer
          format: int
          example: 10
        fk_id_planos:
          type: integer
          format: int
          example: 10
        assinatura_ativa:
          type: boolean
          format: boolean
          example: true
        data_inicio:
          type: string
          format: date
          example: 2023-11-29
        data_fim:
          type: string
          format: date
          example: 2023-12-01
    AssinaturaSucessfull:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Assinatura criada com sucesso
    AssinaturaDesativada:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Assinatura desativada com sucesso
    assinaturaNotFound:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: assinatura não encontrada
    UsuarioJaAssinou:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Usuário já possui uma assinatura ativa
    UsuarioSemAssinatura:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Usuário não possui uma assinatura ativa
    UsuarioNotFound:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Usuario não encontrado
    AssinaturaUsuarioNotFound:
      type: object
      properties:
        mensagem: 
          type: string
          format: string
          example: Nenhuma assinatura ativa encontrada para esse usuário