openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    Essa é a documentação de um WebServer de assinaturas
  
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:3000/

tags:
  - name: planos
    description: tudo sobre planos

  - name: assinatura
    description: tudo sobre assinatura


  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /planos:
    get:
      tags:
        - planos
      summary: Retorna todos os planos existentes
      description: Retorna todos os planos existentes
      operationId: getPlanos
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planos'
        '500':
          description: Internal Server Error
    post:
      tags:
        - planos
      summary: Insere um novo plano
      description: Insere um novo plano
      operationId: postPlanos
      requestBody:
        description: Criando um objeto de plano
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanosSemID'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planos'
        '500':
          description: Internal Server Error
  /planos/{id}:
    get:
      tags:
        - planos
      summary: busca um plano por id
      description: busca e retorna um plano por id
      operationId: getPlanosById
      parameters:
        - name: id
          in: path
          description: ID do plano que será retornado
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planos'
        '500':
          description: Internal Server Error
    put:
      tags:
        - planos
      summary: atualiza um plano
      description: atualiza e retorna um plano
      operationId: putPlanos
      parameters:
        - name: id
          in: path
          description: ID do plano que será retornado
          required: true
          schema:
            type: integer
            format: int
      requestBody:
        description: Criando um objeto de plano
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanosSemID'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planos'
        '500':
          description: Internal Server Error
    delete:
      tags:
        - planos
      summary: atualiza um plano
      description: atualiza e retorna um plano
      operationId: deletePlanos
      parameters:
        - name: id
          in: path
          description: ID do plano que será retornado
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: successful operation
        '500':
          description: Internal Server Error
  
  /assinatura:
    get:
      tags:
        - assinatura
      summary: Retorna todos as assinatura existentes
      description: Retorna todos as assinatura existentes
      operationId: getAssinatura
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assinatura'
        '500':
          description: Internal Server Error
    post:
      tags:
        - assinatura
      summary: Insere uma nova assinatura
      description: Insere uma nova assinatura
      operationId: postAssinatura
      requestBody:
        description: Criando um objeto de assinatura
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssinaturaSemId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Assinatura'
        '500':
          description: Internal Server Error
  
  /assinatura/{id}:
    get:
      tags:
        - assinatura
      summary: busca uma assinatura por id
      description: busca e retorna um assinatura por id
      operationId: getAssinaturaById
      parameters:
        - name: id
          in: path
          description: ID do assinatura que será retornada
          required: true
          schema:
            type: integer
            format: int
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planos'
        '500':
          description: Internal Server Error
    put:
      tags:
        - assinatura
      summary: atualiza uma assinatura
      description: atualiza e retorna uma assinatura
      operationId: putAssinatura
      parameters:
        - name: id
          in: path
          description: ID da assinatura que será retornada
          required: true
          schema:
            type: integer
            format: int
      requestBody:
        description: corpo com modificações da assinatura
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssinaturaSemId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssinaturaSemId'
        '500':
          description: Internal Server Error
components:
  schemas:
    Planos:
      type: object
      properties:
        id_plano:
          type: integer
          format: int
          example: 10
        nome_plano:
          type: string
          format: varchar45
          example: platina
        valor:
          type: number
          format: float
          example: 99.90
    PlanosSemID:
      type: object
      properties:
        nome_plano:
          type: string
          format: varchar45
          example: platina
        valor:
          type: number
          format: float
          example: 99.90
    
    Assinatura:
      type: object
      properties:
        id_assinatura:
          type: integer
          format: int
          example: 10
        id_usuario:
          type: integer
          format: int
          example: 10
        fk_id_planos:
          type: integer
          format: int
          example: 10
        assinatura_ativa:
          type: boolean
          format: boolean
          example: true
        data_inicio:
          type: string
          format: date
          example: 2023-11-29
        data_fim:
          type: string
          format: date
          example: 2023-12-01
    
    AssinaturaSemId:
      type: object
      properties:
        id_usuario:
          type: integer
          format: int
          example: 10
        fk_id_planos:
          type: integer
          format: int
          example: 10
        assinatura_ativa:
          type: boolean
          format: boolean
          example: true
        data_inicio:
          type: string
          format: date
          example: 2023-11-29
        data_fim:
          type: string
          format: date
          example: 2023-12-01